#（一区）=============================（clash配置）
#dns可自行修改
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
dns:
    enable: true
    ipv6: false
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: ['https://doh-pure.onedns.net/dns-query', 'https://ada.openbld.net/dns-query', 'https://223.5.5.5/dns-query', 'https://223.6.6.6/dns-query']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
 
# 出站策略，根据自己情况调整每个策略里分组排序，增删都可以，比如把美国自动放到第一个，比如删除香港故转，注意别漏掉表情逗号等。
# 如果相应分组没有筛选到对应的国家，请根据自己节点名字调整筛选关键字。
# 没有再使用锚点，是考虑很多新手修改难度，这样新手修改某个分组更容易些。
proxy-groups:
- name: 选择代理节点
  type: select
  proxies:
    - DIRECT
    - RN-US
    - BV-TW
    - BV-HK
    - NAT-HK
    - BVHK>RN
    - BVHK>TW
    
- name: TVB
  type: select
  proxies:                                           #自定义添加协议的name字段
    - RN-US
    - BV-TW
    - BV-HK
    - NAT-HK

- name: 国外流媒体
  type: select
  proxies:
    - RN-US
    - BV-TW
    - BV-HK
    - NAT-HK
    - BVHK>RN
    - BVHK>TW

- name: YouTube
  type: select
  proxies:
    - RN-US
    - BV-TW
    - BV-HK
    - NAT-HK
    - BVHK>RN
    - BVHK>TW

- name: Google
  type: select
  proxies:
    - RN-US
    - BV-TW
    - BV-HK
    - NAT-HK
    - BVHK>RN
    - BVHK>TW

- name: openAI
  type: select
  proxies:
    - RN-US
    - BV-TW
    - BVHK>RN
    - BVHK>TW

- name: Apple
  type: select
  proxies:
    - DIRECT
    - RN-US
    - BV-TW
    - BV-HK
    - NAT-HK
    - BVHK>RN
    - BVHK>TW

- name: RN-US
  type: url-test
  url: http://www.apple.com/library/test/success.html
  interval: 180
  tolerance: 100
  proxies:
    - RN-US1
    - RN-US2
    - RN-US3
    - RN-US4
    - RN-US5
    - RN-US6

- name: BV-TW
  type: url-test
  url: http://www.apple.com/library/test/success.html
  interval: 180
  tolerance: 100
  proxies:
    - BV-TW1
    - BV-TW2
    - BV-TW3
    - BV-TW4
    - BV-TW5
    - BV-TW6

- name: BV-HK
  type: url-test
  url: http://www.apple.com/library/test/success.html
  interval: 180
  tolerance: 100
  proxies:
    - BV-HK1
    - BV-HK2
    - BV-HK3
    - BV-HK4
    - BV-HK5
    - BV-HK6

- name: NAT-HK
  type: url-test
  url: http://www.apple.com/library/test/success.html
  interval: 180
  tolerance: 100
  proxies:
    - NAT-HK1
    - NAT-HK2
    - NAT-HK3
    - NAT-HK4
    - NAT-HK5
    - NAT-HK6

- name: BVHK>RN
  type: relay
  proxies:
    - BV-HK
    - RN-US

- name: BVHK>TW
  type: relay
  proxies:
    - BV-HK
    - BV-TW

#（四区）==============================（代理规则）
#代理规则可自行添加 

rules:
  - DOMAIN,gspe1-ssl.ls.apple.com,openAI
  - GEOSITE,openai,openAI
  - DOMAIN,apple-relay.apple.com,openAI
  - DOMAIN,apple-relay.cloudflare.com,openAI
  - DOMAIN-KEYWORD,tvb,TVB
  - DOMAIN-KEYWORD,mytvsuper,TVB
  - GEOSITE,youtube,YouTube
  - GEOSITE,google,Google
  - DOMAIN-KEYWORD,androidtv,Google
  - GEOSITE,netflix,国外流媒体
  - GEOSITE,apple,Apple
  - DOMAIN-KEYWORD,disneyplus,国外流媒体
  - DOMAIN-KEYWORD,aktv,国外流媒体
  - GEOIP,LAN,DIRECT
  - GEOSITE,CN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,选择代理节点
